# Pandas
- Pandas is a popular library in Python used for data analysis and manipulation. It helps you work with structured data like tables (similar to Excel spreadsheets or SQL tables).

### What Pandas is used for
- Cleaning and preparing data
- Reading/writing data (CSV, Excel, databases, etc.)
- Filtering, sorting, and grouping data
- Performing calculations and statistics
- Handling missing values
- It’s powerful, easy to use, and integrates well with other tools like:  NumPy (for numerical operations), Matplotlib / Seaborn (for visualization), Machine learning libraries
### Core data structures
- Series → a single column (1D data)
- DataFrame → a table (rows and columns)
- different operations

In [4]:
pip install pandas

Requirement already satisfied: pandas in c:\users\maha4\appdata\local\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\maha4\appdata\local\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\maha4\appdata\local\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\maha4\appdata\local\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\maha4\appdata\local\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\maha4\appdata\local\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install numpy

Requirement already satisfied: numpy in c:\users\maha4\appdata\local\anaconda3\lib\site-packages (2.3.5)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1', 'Row2', 'Row3', 'Row4', 'Row5'], columns=['Col1', 'Col2', 'Col3', 'Col4'])
print(df)

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [5]:
df.to_csv('myDataFrame.csv')

In [6]:
# accessing the element of the dataframe
# .loc Labels / Names "a", "Age" (index and columns)
# .iloc Integer Positions,0, 1, 2
print(df['Col1'])
print(df.loc["Row1"])

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Col1, dtype: int64
Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int64

In [9]:
df.loc['Row1'] # to get the first row of the dataframe

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int64

In [14]:
df.loc[:,:]

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [15]:
df.loc["Row1":"Row2", "Col1":"Col2"] # to get the first two rows of the dataframe

      Col1  Col2
Row1     0     1
Row2     4     5

In [16]:
df.iloc[0:2, 0:2] # to get the first two rows and first two columns of the dataframe using iloc

      Col1  Col2
Row1     0     1
Row2     4     5

In [52]:
df.iloc[0:3:, 0:2] # to check the type of the dataframe

      Col1  Col2
Row1     0     1
Row2     4     5
Row3     8     9

In [53]:
type(df.loc["Row1"]) # to check the type of the dataframe using loc

pandas.Series

In [57]:
df.iloc[0:3, 0:2] # to get the first two rows and first two columns of the dataframe using iloc

      Col1  Col2
Row1     0     1
Row2     4     5
Row3     8     9

In [18]:
type(df.iloc[0:3, 0:]) # to check the type of the dataframe

pandas.DataFrame

In [19]:
df.iloc[0:, 1:]

      Col2  Col3  Col4
Row1     1     2     3
Row2     5     6     7
Row3     9    10    11
Row4    13    14    15
Row5    17    18    19

In [21]:
# dataframe converted to numpy array
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [62]:
df.iloc[0:3, 0:2].values # to get the first two rows and first two columns of the dataframe using iloc

array([[0, 1],
       [4, 5],
       [8, 9]])

In [24]:
df.iloc[0:3,0:2].values.shape # to check the shape of the dataframe

(3, 2)

In [25]:
df.isnull()

       Col1   Col2   Col3   Col4
Row1  False  False  False  False
Row2  False  False  False  False
Row3  False  False  False  False
Row4  False  False  False  False
Row5  False  False  False  False

In [27]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [28]:
df

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [31]:
df["Col3"]

Row1     2
Row2     6
Row3    10
Row4    14
Row5    18
Name: Col3, dtype: int64

In [32]:
df[["Col1", "Col2"]]

      Col1  Col2
Row1     0     1
Row2     4     5
Row3     8     9
Row4    12    13
Row5    16    17

In [33]:
df["Col1"].unique()

array([ 0,  4,  8, 12, 16])

In [3]:
df2=pd.read_csv('myDataFrame.csv', sep=',')
df2.head()

  Unnamed: 0  Col1  Col2  Col3  Col4
0       Row1     0     1     2     3
1       Row2     4     5     6     7
2       Row3     8     9    10    11
3       Row4    12    13    14    15
4       Row5    16    17    18    19

In [4]:
df2=pd.read_csv('benz.csv')

In [5]:
df2.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), str(8)
memory usage: 12.1 MB

In [7]:
df2.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
df2['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
ai     34
m      34
e      32
ba     27
at     25
a      21
ax     19
am     18
aq     18
i      18
u      17
l      16
aw     16
ad     14
k      11
b      11
au     11
as     10
r      10
bc      6
ao      4
c       3
q       2
aa      2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [12]:
df2[df2['y']>100]

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4202,8402,123.34,ap,l,s,c,d,aa,d,r,...,0,0,0,0,0,0,0,0,0,0
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [7]:

from io import StringIO, BytesIO

In [8]:
data=('col1,col2,col3\n'
       'a,b,1\n'
       'c,d,2\n'
       'e,f,3')

In [9]:
type(data)

str

In [10]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    a    b     1
1    c    d     2
2    e    f     3

In [11]:
# get secific cols 

df=pd.read_csv(StringIO(data), usecols=['col1','col2'])
print(df)

  col1 col2
0    a    b
1    c    d
2    e    f

In [12]:
df.to_csv('test.csv')

In [13]:
# secifying cloms data types

data =('a,b,c,d\n'
    '1,2,3,4\n'
    '5,6,7,8\n'
    '9,10,11,12')

In [14]:
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12

In [15]:
df=pd.read_csv(StringIO(data),dtype='object')
print(df)

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [16]:
df['a']

0    1
1    5
2    9
Name: a, dtype: object

In [17]:
df=pd.read_csv(StringIO(data),dtype={'b':int,'c':float,'a':'Int64'})
df

   a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [18]:
df['a'][1]

np.int64(5)

In [89]:
df.dtypes

a      Int64
b      int64
c    float64
d      int64
dtype: object

In [8]:
data1= ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,orange,cow,10')

In [9]:
pd.read_csv(StringIO(data1),index_col=0)

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [10]:
data1= ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow,')

In [11]:
pd.read_csv(StringIO(data1))

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [12]:

pd.read_csv(StringIO(data1),index_col=False)

   a       b    c
0  4   apple  bat
1  8  orange  cow

In [14]:
# combling usecols and index_col
pd.read_csv(StringIO(data1),usecols=['b','c'],index_col=False)

        b    c
0   apple  bat
1  orange  cow

### Read Json to CSV

In [3]:
data= '{"Empname":"maha","email":"maha@gmail.com","jobprofile":[{"jobtitle1":"Teamlead","jobtitle2":"AI ML Engg"}]}'

In [4]:
df1=pd.read_json(data)
df1

C:\Users\maha4\AppData\Local\Temp\ipykernel_5516\1862705023.py:1: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df1=pd.read_json(data)

  Empname           email                                         jobprofile
0    maha  maha@gmail.com  {'jobtitle1': 'Teamlead', 'jobtitle2': 'AI ML ...

In [38]:
url = "https://jsonplaceholder.typicode.com/users"

df = pd.read_json(url)

df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [39]:
# convert json to csv
df.to_csv('users.csv')

In [40]:
df.to_json(orient="index")

'{"0":{"id":1,"name":"Leanne Graham","username":"Bret","email":"Sincere@april.biz","address":{"street":"Kulas Light","suite":"Apt. 556","city":"Gwenborough","zipcode":"92998-3874","geo":{"lat":"-37.3159","lng":"81.1496"}},"phone":"1-770-736-8031 x56442","website":"hildegard.org","company":{"name":"Romaguera-Crona","catchPhrase":"Multi-layered client-server neural-net","bs":"harness real-time e-markets"}},"1":{"id":2,"name":"Ervin Howell","username":"Antonette","email":"Shanna@melissa.tv","address":{"street":"Victor Plains","suite":"Suite 879","city":"Wisokyburgh","zipcode":"90566-7771","geo":{"lat":"-43.9509","lng":"-34.4618"}},"phone":"010-692-6593 x09125","website":"anastasia.net","company":{"name":"Deckow-Crist","catchPhrase":"Proactive didactic contingency","bs":"synergize scalable supply-chains"}},"2":{"id":3,"name":"Clementine Bauch","username":"Samantha","email":"Nathan@yesenia.net","address":{"street":"Douglas Extension","suite":"Suite 847","city":"McKenziehaven","zipcode":"59590-4157","geo":{"lat":"-68.6102","lng":"-47.0653"}},"phone":"1-463-123-4447","website":"ramiro.info","company":{"name":"Romaguera-Jacobson","catchPhrase":"Face to face bifurcated interface","bs":"e-enable strategic applications"}},"3":{"id":4,"name":"Patricia Lebsack","username":"Karianne","email":"Julianne.OConner@kory.org","address":{"street":"Hoeger Mall","suite":"Apt. 692","city":"South Elvis","zipcode":"53919-4257","geo":{"lat":"29.4572","lng":"-164.2990"}},"phone":"493-170-9623 x156","website":"kale.biz","company":{"name":"Robel-Corkery","catchPhrase":"Multi-tiered zero tolerance productivity","bs":"transition cutting-edge web services"}},"4":{"id":5,"name":"Chelsey Dietrich","username":"Kamren","email":"Lucio_Hettinger@annie.ca","address":{"street":"Skiles Walks","suite":"Suite 351","city":"Roscoeview","zipcode":"33263","geo":{"lat":"-31.8129","lng":"62.5342"}},"phone":"(254)954-1289","website":"demarco.info","company":{"name":"Keebler LLC","catchPhrase":"User-centric fault-tolerant solution","bs":"revolutionize end-to-end systems"}},"5":{"id":6,"name":"Mrs. Dennis Schulist","username":"Leopoldo_Corkery","email":"Karley_Dach@jasper.info","address":{"street":"Norberto Crossing","suite":"Apt. 950","city":"South Christy","zipcode":"23505-1337","geo":{"lat":"-71.4197","lng":"71.7478"}},"phone":"1-477-935-8478 x6430","website":"ola.org","company":{"name":"Considine-Lockman","catchPhrase":"Synchronised bottom-line interface","bs":"e-enable innovative applications"}},"6":{"id":7,"name":"Kurtis Weissnat","username":"Elwyn.Skiles","email":"Telly.Hoeger@billy.biz","address":{"street":"Rex Trail","suite":"Suite 280","city":"Howemouth","zipcode":"58804-1099","geo":{"lat":"24.8918","lng":"21.8984"}},"phone":"210.067.6132","website":"elvis.io","company":{"name":"Johns Group","catchPhrase":"Configurable multimedia task-force","bs":"generate enterprise e-tailers"}},"7":{"id":8,"name":"Nicholas Runolfsdottir V","username":"Maxime_Nienow","email":"Sherwood@rosamond.me","address":{"street":"Ellsworth Summit","suite":"Suite 729","city":"Aliyaview","zipcode":"45169","geo":{"lat":"-14.3990","lng":"-120.7677"}},"phone":"586.493.6943 x140","website":"jacynthe.com","company":{"name":"Abernathy Group","catchPhrase":"Implemented secondary concept","bs":"e-enable extensible e-tailers"}},"8":{"id":9,"name":"Glenna Reichert","username":"Delphine","email":"Chaim_McDermott@dana.io","address":{"street":"Dayna Park","suite":"Suite 449","city":"Bartholomebury","zipcode":"76495-3109","geo":{"lat":"24.6463","lng":"-168.8889"}},"phone":"(775)976-6794 x41206","website":"conrad.com","company":{"name":"Yost and Sons","catchPhrase":"Switchable contextually-based project","bs":"aggregate real-time technologies"}},"9":{"id":10,"name":"Clementina DuBuque","username":"Moriah.Stanton","email":"Rey.Padberg@karina.biz","address":{"street":"Kattie Turnpike","suite":"Suite 198","city":"Lebsackbury","zipcode":"31428-2261","geo":{"lat":"-38.2386","lng":"57.2232"}},"phone":"024-648-3804","website":"ambrose.net","company":{"name":"Hoeger LLC","catchPhrase":"Centralized empowering task-force","bs":"target end-to-end models"}}}'

In [43]:
df.to_json()

'{"id":{"0":1,"1":2,"2":3,"3":4,"4":5,"5":6,"6":7,"7":8,"8":9,"9":10},"name":{"0":"Leanne Graham","1":"Ervin Howell","2":"Clementine Bauch","3":"Patricia Lebsack","4":"Chelsey Dietrich","5":"Mrs. Dennis Schulist","6":"Kurtis Weissnat","7":"Nicholas Runolfsdottir V","8":"Glenna Reichert","9":"Clementina DuBuque"},"username":{"0":"Bret","1":"Antonette","2":"Samantha","3":"Karianne","4":"Kamren","5":"Leopoldo_Corkery","6":"Elwyn.Skiles","7":"Maxime_Nienow","8":"Delphine","9":"Moriah.Stanton"},"email":{"0":"Sincere@april.biz","1":"Shanna@melissa.tv","2":"Nathan@yesenia.net","3":"Julianne.OConner@kory.org","4":"Lucio_Hettinger@annie.ca","5":"Karley_Dach@jasper.info","6":"Telly.Hoeger@billy.biz","7":"Sherwood@rosamond.me","8":"Chaim_McDermott@dana.io","9":"Rey.Padberg@karina.biz"},"address":{"0":{"street":"Kulas Light","suite":"Apt. 556","city":"Gwenborough","zipcode":"92998-3874","geo":{"lat":"-37.3159","lng":"81.1496"}},"1":{"street":"Victor Plains","suite":"Suite 879","city":"Wisokyburgh","zipcode":"90566-7771","geo":{"lat":"-43.9509","lng":"-34.4618"}},"2":{"street":"Douglas Extension","suite":"Suite 847","city":"McKenziehaven","zipcode":"59590-4157","geo":{"lat":"-68.6102","lng":"-47.0653"}},"3":{"street":"Hoeger Mall","suite":"Apt. 692","city":"South Elvis","zipcode":"53919-4257","geo":{"lat":"29.4572","lng":"-164.2990"}},"4":{"street":"Skiles Walks","suite":"Suite 351","city":"Roscoeview","zipcode":"33263","geo":{"lat":"-31.8129","lng":"62.5342"}},"5":{"street":"Norberto Crossing","suite":"Apt. 950","city":"South Christy","zipcode":"23505-1337","geo":{"lat":"-71.4197","lng":"71.7478"}},"6":{"street":"Rex Trail","suite":"Suite 280","city":"Howemouth","zipcode":"58804-1099","geo":{"lat":"24.8918","lng":"21.8984"}},"7":{"street":"Ellsworth Summit","suite":"Suite 729","city":"Aliyaview","zipcode":"45169","geo":{"lat":"-14.3990","lng":"-120.7677"}},"8":{"street":"Dayna Park","suite":"Suite 449","city":"Bartholomebury","zipcode":"76495-3109","geo":{"lat":"24.6463","lng":"-168.8889"}},"9":{"street":"Kattie Turnpike","suite":"Suite 198","city":"Lebsackbury","zipcode":"31428-2261","geo":{"lat":"-38.2386","lng":"57.2232"}}},"phone":{"0":"1-770-736-8031 x56442","1":"010-692-6593 x09125","2":"1-463-123-4447","3":"493-170-9623 x156","4":"(254)954-1289","5":"1-477-935-8478 x6430","6":"210.067.6132","7":"586.493.6943 x140","8":"(775)976-6794 x41206","9":"024-648-3804"},"website":{"0":"hildegard.org","1":"anastasia.net","2":"ramiro.info","3":"kale.biz","4":"demarco.info","5":"ola.org","6":"elvis.io","7":"jacynthe.com","8":"conrad.com","9":"ambrose.net"},"company":{"0":{"name":"Romaguera-Crona","catchPhrase":"Multi-layered client-server neural-net","bs":"harness real-time e-markets"},"1":{"name":"Deckow-Crist","catchPhrase":"Proactive didactic contingency","bs":"synergize scalable supply-chains"},"2":{"name":"Romaguera-Jacobson","catchPhrase":"Face to face bifurcated interface","bs":"e-enable strategic applications"},"3":{"name":"Robel-Corkery","catchPhrase":"Multi-tiered zero tolerance productivity","bs":"transition cutting-edge web services"},"4":{"name":"Keebler LLC","catchPhrase":"User-centric fault-tolerant solution","bs":"revolutionize end-to-end systems"},"5":{"name":"Considine-Lockman","catchPhrase":"Synchronised bottom-line interface","bs":"e-enable innovative applications"},"6":{"name":"Johns Group","catchPhrase":"Configurable multimedia task-force","bs":"generate enterprise e-tailers"},"7":{"name":"Abernathy Group","catchPhrase":"Implemented secondary concept","bs":"e-enable extensible e-tailers"},"8":{"name":"Yost and Sons","catchPhrase":"Switchable contextually-based project","bs":"aggregate real-time technologies"},"9":{"name":"Hoeger LLC","catchPhrase":"Centralized empowering task-force","bs":"target end-to-end models"}}}'

In [42]:
df.to_json(orient='records')

'[{"id":1,"name":"Leanne Graham","username":"Bret","email":"Sincere@april.biz","address":{"street":"Kulas Light","suite":"Apt. 556","city":"Gwenborough","zipcode":"92998-3874","geo":{"lat":"-37.3159","lng":"81.1496"}},"phone":"1-770-736-8031 x56442","website":"hildegard.org","company":{"name":"Romaguera-Crona","catchPhrase":"Multi-layered client-server neural-net","bs":"harness real-time e-markets"}},{"id":2,"name":"Ervin Howell","username":"Antonette","email":"Shanna@melissa.tv","address":{"street":"Victor Plains","suite":"Suite 879","city":"Wisokyburgh","zipcode":"90566-7771","geo":{"lat":"-43.9509","lng":"-34.4618"}},"phone":"010-692-6593 x09125","website":"anastasia.net","company":{"name":"Deckow-Crist","catchPhrase":"Proactive didactic contingency","bs":"synergize scalable supply-chains"}},{"id":3,"name":"Clementine Bauch","username":"Samantha","email":"Nathan@yesenia.net","address":{"street":"Douglas Extension","suite":"Suite 847","city":"McKenziehaven","zipcode":"59590-4157","geo":{"lat":"-68.6102","lng":"-47.0653"}},"phone":"1-463-123-4447","website":"ramiro.info","company":{"name":"Romaguera-Jacobson","catchPhrase":"Face to face bifurcated interface","bs":"e-enable strategic applications"}},{"id":4,"name":"Patricia Lebsack","username":"Karianne","email":"Julianne.OConner@kory.org","address":{"street":"Hoeger Mall","suite":"Apt. 692","city":"South Elvis","zipcode":"53919-4257","geo":{"lat":"29.4572","lng":"-164.2990"}},"phone":"493-170-9623 x156","website":"kale.biz","company":{"name":"Robel-Corkery","catchPhrase":"Multi-tiered zero tolerance productivity","bs":"transition cutting-edge web services"}},{"id":5,"name":"Chelsey Dietrich","username":"Kamren","email":"Lucio_Hettinger@annie.ca","address":{"street":"Skiles Walks","suite":"Suite 351","city":"Roscoeview","zipcode":"33263","geo":{"lat":"-31.8129","lng":"62.5342"}},"phone":"(254)954-1289","website":"demarco.info","company":{"name":"Keebler LLC","catchPhrase":"User-centric fault-tolerant solution","bs":"revolutionize end-to-end systems"}},{"id":6,"name":"Mrs. Dennis Schulist","username":"Leopoldo_Corkery","email":"Karley_Dach@jasper.info","address":{"street":"Norberto Crossing","suite":"Apt. 950","city":"South Christy","zipcode":"23505-1337","geo":{"lat":"-71.4197","lng":"71.7478"}},"phone":"1-477-935-8478 x6430","website":"ola.org","company":{"name":"Considine-Lockman","catchPhrase":"Synchronised bottom-line interface","bs":"e-enable innovative applications"}},{"id":7,"name":"Kurtis Weissnat","username":"Elwyn.Skiles","email":"Telly.Hoeger@billy.biz","address":{"street":"Rex Trail","suite":"Suite 280","city":"Howemouth","zipcode":"58804-1099","geo":{"lat":"24.8918","lng":"21.8984"}},"phone":"210.067.6132","website":"elvis.io","company":{"name":"Johns Group","catchPhrase":"Configurable multimedia task-force","bs":"generate enterprise e-tailers"}},{"id":8,"name":"Nicholas Runolfsdottir V","username":"Maxime_Nienow","email":"Sherwood@rosamond.me","address":{"street":"Ellsworth Summit","suite":"Suite 729","city":"Aliyaview","zipcode":"45169","geo":{"lat":"-14.3990","lng":"-120.7677"}},"phone":"586.493.6943 x140","website":"jacynthe.com","company":{"name":"Abernathy Group","catchPhrase":"Implemented secondary concept","bs":"e-enable extensible e-tailers"}},{"id":9,"name":"Glenna Reichert","username":"Delphine","email":"Chaim_McDermott@dana.io","address":{"street":"Dayna Park","suite":"Suite 449","city":"Bartholomebury","zipcode":"76495-3109","geo":{"lat":"24.6463","lng":"-168.8889"}},"phone":"(775)976-6794 x41206","website":"conrad.com","company":{"name":"Yost and Sons","catchPhrase":"Switchable contextually-based project","bs":"aggregate real-time technologies"}},{"id":10,"name":"Clementina DuBuque","username":"Moriah.Stanton","email":"Rey.Padberg@karina.biz","address":{"street":"Kattie Turnpike","suite":"Suite 198","city":"Lebsackbury","zipcode":"31428-2261","geo":{"lat":"-38.2386","lng":"57.2232"}},"phone":"024-648-3804","website":"ambrose.net","company":{"name":"Hoeger LLC","catchPhrase":"Centralized empowering task-force","bs":"target end-to-end models"}}]'

In [49]:
df1

  Empname           email                                         jobprofile
0    maha  maha@gmail.com  {'jobtitle1': 'Teamlead', 'jobtitle2': 'AI ML ...

In [50]:
df.to_json(orient="records")

'[{"id":1,"name":"Leanne Graham","username":"Bret","email":"Sincere@april.biz","address":{"street":"Kulas Light","suite":"Apt. 556","city":"Gwenborough","zipcode":"92998-3874","geo":{"lat":"-37.3159","lng":"81.1496"}},"phone":"1-770-736-8031 x56442","website":"hildegard.org","company":{"name":"Romaguera-Crona","catchPhrase":"Multi-layered client-server neural-net","bs":"harness real-time e-markets"}},{"id":2,"name":"Ervin Howell","username":"Antonette","email":"Shanna@melissa.tv","address":{"street":"Victor Plains","suite":"Suite 879","city":"Wisokyburgh","zipcode":"90566-7771","geo":{"lat":"-43.9509","lng":"-34.4618"}},"phone":"010-692-6593 x09125","website":"anastasia.net","company":{"name":"Deckow-Crist","catchPhrase":"Proactive didactic contingency","bs":"synergize scalable supply-chains"}},{"id":3,"name":"Clementine Bauch","username":"Samantha","email":"Nathan@yesenia.net","address":{"street":"Douglas Extension","suite":"Suite 847","city":"McKenziehaven","zipcode":"59590-4157","geo":{"lat":"-68.6102","lng":"-47.0653"}},"phone":"1-463-123-4447","website":"ramiro.info","company":{"name":"Romaguera-Jacobson","catchPhrase":"Face to face bifurcated interface","bs":"e-enable strategic applications"}},{"id":4,"name":"Patricia Lebsack","username":"Karianne","email":"Julianne.OConner@kory.org","address":{"street":"Hoeger Mall","suite":"Apt. 692","city":"South Elvis","zipcode":"53919-4257","geo":{"lat":"29.4572","lng":"-164.2990"}},"phone":"493-170-9623 x156","website":"kale.biz","company":{"name":"Robel-Corkery","catchPhrase":"Multi-tiered zero tolerance productivity","bs":"transition cutting-edge web services"}},{"id":5,"name":"Chelsey Dietrich","username":"Kamren","email":"Lucio_Hettinger@annie.ca","address":{"street":"Skiles Walks","suite":"Suite 351","city":"Roscoeview","zipcode":"33263","geo":{"lat":"-31.8129","lng":"62.5342"}},"phone":"(254)954-1289","website":"demarco.info","company":{"name":"Keebler LLC","catchPhrase":"User-centric fault-tolerant solution","bs":"revolutionize end-to-end systems"}},{"id":6,"name":"Mrs. Dennis Schulist","username":"Leopoldo_Corkery","email":"Karley_Dach@jasper.info","address":{"street":"Norberto Crossing","suite":"Apt. 950","city":"South Christy","zipcode":"23505-1337","geo":{"lat":"-71.4197","lng":"71.7478"}},"phone":"1-477-935-8478 x6430","website":"ola.org","company":{"name":"Considine-Lockman","catchPhrase":"Synchronised bottom-line interface","bs":"e-enable innovative applications"}},{"id":7,"name":"Kurtis Weissnat","username":"Elwyn.Skiles","email":"Telly.Hoeger@billy.biz","address":{"street":"Rex Trail","suite":"Suite 280","city":"Howemouth","zipcode":"58804-1099","geo":{"lat":"24.8918","lng":"21.8984"}},"phone":"210.067.6132","website":"elvis.io","company":{"name":"Johns Group","catchPhrase":"Configurable multimedia task-force","bs":"generate enterprise e-tailers"}},{"id":8,"name":"Nicholas Runolfsdottir V","username":"Maxime_Nienow","email":"Sherwood@rosamond.me","address":{"street":"Ellsworth Summit","suite":"Suite 729","city":"Aliyaview","zipcode":"45169","geo":{"lat":"-14.3990","lng":"-120.7677"}},"phone":"586.493.6943 x140","website":"jacynthe.com","company":{"name":"Abernathy Group","catchPhrase":"Implemented secondary concept","bs":"e-enable extensible e-tailers"}},{"id":9,"name":"Glenna Reichert","username":"Delphine","email":"Chaim_McDermott@dana.io","address":{"street":"Dayna Park","suite":"Suite 449","city":"Bartholomebury","zipcode":"76495-3109","geo":{"lat":"24.6463","lng":"-168.8889"}},"phone":"(775)976-6794 x41206","website":"conrad.com","company":{"name":"Yost and Sons","catchPhrase":"Switchable contextually-based project","bs":"aggregate real-time technologies"}},{"id":10,"name":"Clementina DuBuque","username":"Moriah.Stanton","email":"Rey.Padberg@karina.biz","address":{"street":"Kattie Turnpike","suite":"Suite 198","city":"Lebsackbury","zipcode":"31428-2261","geo":{"lat":"-38.2386","lng":"57.2232"}},"phone":"024-648-3804","website":"ambrose.net","company":{"name":"Hoeger LLC","catchPhrase":"Centralized empowering task-force","bs":"target end-to-end models"}}]'

In [53]:
df2=pd.read_csv('wine.csv')
df2.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [56]:
df2.to_json('wine.json')
df2

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [57]:
df2.to_json(orient="records")

'[{"Unnamed: 0":0,"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"Unnamed: 0":1,"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"Unnamed: 0":2,"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"Unnamed: 0":3,"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"Unnamed: 0":4,"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"Unnamed: 0":5,"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"Unnamed: 0":6,"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"Unnamed: 0":7,"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"12":3.58,"13":1295},{"Unnamed: 0":8,"0":1,"1":14.83,"2":1.64,"3":2.17,"4":14.0,"5":97,"6":2.8,"7":2.98,"8":0.29,"9":1.98,"10":5.2,"11":1.08,"12":2.85,"13":1045},{"Unnamed: 0":9,"0":1,"1":13.86,"2":1.35,"3":2.27,"4":16.0,"5":98,"6":2.98,"7":3.15,"8":0.22,"9":1.85,"10":7.22,"11":1.01,"12":3.55,"13":1045},{"Unnamed: 0":10,"0":1,"1":14.1,"2":2.16,"3":2.3,"4":18.0,"5":105,"6":2.95,"7":3.32,"8":0.22,"9":2.38,"10":5.75,"11":1.25,"12":3.17,"13":1510},{"Unnamed: 0":11,"0":1,"1":14.12,"2":1.48,"3":2.32,"4":16.8,"5":95,"6":2.2,"7":2.43,"8":0.26,"9":1.57,"10":5.0,"11":1.17,"12":2.82,"13":1280},{"Unnamed: 0":12,"0":1,"1":13.75,"2":1.73,"3":2.41,"4":16.0,"5":89,"6":2.6,"7":2.76,"8":0.29,"9":1.81,"10":5.6,"11":1.15,"12":2.9,"13":1320},{"Unnamed: 0":13,"0":1,"1":14.75,"2":1.73,"3":2.39,"4":11.4,"5":91,"6":3.1,"7":3.69,"8":0.43,"9":2.81,"10":5.4,"11":1.25,"12":2.73,"13":1150},{"Unnamed: 0":14,"0":1,"1":14.38,"2":1.87,"3":2.38,"4":12.0,"5":102,"6":3.3,"7":3.64,"8":0.29,"9":2.96,"10":7.5,"11":1.2,"12":3.0,"13":1547},{"Unnamed: 0":15,"0":1,"1":13.63,"2":1.81,"3":2.7,"4":17.2,"5":112,"6":2.85,"7":2.91,"8":0.3,"9":1.46,"10":7.3,"11":1.28,"12":2.88,"13":1310},{"Unnamed: 0":16,"0":1,"1":14.3,"2":1.92,"3":2.72,"4":20.0,"5":120,"6":2.8,"7":3.14,"8":0.33,"9":1.97,"10":6.2,"11":1.07,"12":2.65,"13":1280},{"Unnamed: 0":17,"0":1,"1":13.83,"2":1.57,"3":2.62,"4":20.0,"5":115,"6":2.95,"7":3.4,"8":0.4,"9":1.72,"10":6.6,"11":1.13,"12":2.57,"13":1130},{"Unnamed: 0":18,"0":1,"1":14.19,"2":1.59,"3":2.48,"4":16.5,"5":108,"6":3.3,"7":3.93,"8":0.32,"9":1.86,"10":8.7,"11":1.23,"12":2.82,"13":1680},{"Unnamed: 0":19,"0":1,"1":13.64,"2":3.1,"3":2.56,"4":15.2,"5":116,"6":2.7,"7":3.03,"8":0.17,"9":1.66,"10":5.1,"11":0.96,"12":3.36,"13":845},{"Unnamed: 0":20,"0":1,"1":14.06,"2":1.63,"3":2.28,"4":16.0,"5":126,"6":3.0,"7":3.17,"8":0.24,"9":2.1,"10":5.65,"11":1.09,"12":3.71,"13":780},{"Unnamed: 0":21,"0":1,"1":12.93,"2":3.8,"3":2.65,"4":18.6,"5":102,"6":2.41,"7":2.41,"8":0.25,"9":1.98,"10":4.5,"11":1.03,"12":3.52,"13":770},{"Unnamed: 0":22,"0":1,"1":13.71,"2":1.86,"3":2.36,"4":16.6,"5":101,"6":2.61,"7":2.88,"8":0.27,"9":1.69,"10":3.8,"11":1.11,"12":4.0,"13":1035},{"Unnamed: 0":23,"0":1,"1":12.85,"2":1.6,"3":2.52,"4":17.8,"5":95,"6":2.48,"7":2.37,"8":0.26,"9":1.46,"10":3.93,"11":1.09,"12":3.63,"13":1015},{"Unnamed: 0":24,"0":1,"1":13.5,"2":1.81,"3":2.61,"4":20.0,"5":96,"6":2.53,"7":2.61,"8":0.28,"9":1.66,"10":3.52,"11":1.12,"12":3.82,"13":845},{"Unnamed: 0":25,"0":1,"1":13.05,"2":2.05,"3":3.22,"4":25.0,"5":124,"6":2.63,"7":2.68,"8":0.47,"9":1.92,"10":3.58,"11":1.13,"12":3.2,"13":830},{"Unnamed: 0":26,"0":1,"1":13.39,"2":1.77,"3":2.62,"4":16.1,"5":93,"6":2.85,"7":2.94,"8":0.34,"9":1.45,"10":4.8,"11":0.92,"12":3.22,"13":1195},{"Unnamed: 0":27,"0":1,"1":13.3,"2":1.72,"3":2.14,"4":17.0,"5":94,"6":2.4,"7":2.19,"8":0.27,"9":1.35,"10":3.95,"11":1.02,"12":2.77,"13":1285},{"Unnamed: 0":28,"0":1,"1":13.87,"2":1.9,"3":2.8,"4":19.4,"5":107,"6":2.95,"7":2.97,"8":0.37,"9":1.76,"10":4.5,"11":1.25,"12":3.4,"13":915},{"Unnamed: 0":29,"0":1,"1":14.02,"2":1.68,"3":2.21,"4":16.0,"5":96,"6":2.65,"7":2.33,"8":0.26,"9":1.98,"10":4.7,"11":1.04,"12":3.59,"13":1035},{"Unnamed: 0":30,"0":1,"1":13.73,"2":1.5,"3":2.7,"4":22.5,"5":101,"6":3.0,"7":3.25,"8":0.29,"9":2.38,"10":5.7,"11":1.19,"12":2.71,"13":1285},{"Unnamed: 0":31,"0":1,"1":13.58,"2":1.66,"3":2.36,"4":19.1,"5":106,"6":2.86,"7":3.19,"8":0.22,"9":1.95,"10":6.9,"11":1.09,"12":2.88,"13":1515},{"Unnamed: 0":32,"0":1,"1":13.68,"2":1.83,"3":2.36,"4":17.2,"5":104,"6":2.42,"7":2.69,"8":0.42,"9":1.97,"10":3.84,"11":1.23,"12":2.87,"13":990},{"Unnamed: 0":33,"0":1,"1":13.76,"2":1.53,"3":2.7,"4":19.5,"5":132,"6":2.95,"7":2.74,"8":0.5,"9":1.35,"10":5.4,"11":1.25,"12":3.0,"13":1235},{"Unnamed: 0":34,"0":1,"1":13.51,"2":1.8,"3":2.65,"4":19.0,"5":110,"6":2.35,"7":2.53,"8":0.29,"9":1.54,"10":4.2,"11":1.1,"12":2.87,"13":1095},{"Unnamed: 0":35,"0":1,"1":13.48,"2":1.81,"3":2.41,"4":20.5,"5":100,"6":2.7,"7":2.98,"8":0.26,"9":1.86,"10":5.1,"11":1.04,"12":3.47,"13":920},{"Unnamed: 0":36,"0":1,"1":13.28,"2":1.64,"3":2.84,"4":15.5,"5":110,"6":2.6,"7":2.68,"8":0.34,"9":1.36,"10":4.6,"11":1.09,"12":2.78,"13":880},{"Unnamed: 0":37,"0":1,"1":13.05,"2":1.65,"3":2.55,"4":18.0,"5":98,"6":2.45,"7":2.43,"8":0.29,"9":1.44,"10":4.25,"11":1.12,"12":2.51,"13":1105},{"Unnamed: 0":38,"0":1,"1":13.07,"2":1.5,"3":2.1,"4":15.5,"5":98,"6":2.4,"7":2.64,"8":0.28,"9":1.37,"10":3.7,"11":1.18,"12":2.69,"13":1020},{"Unnamed: 0":39,"0":1,"1":14.22,"2":3.99,"3":2.51,"4":13.2,"5":128,"6":3.0,"7":3.04,"8":0.2,"9":2.08,"10":5.1,"11":0.89,"12":3.53,"13":760},{"Unnamed: 0":40,"0":1,"1":13.56,"2":1.71,"3":2.31,"4":16.2,"5":117,"6":3.15,"7":3.29,"8":0.34,"9":2.34,"10":6.13,"11":0.95,"12":3.38,"13":795},{"Unnamed: 0":41,"0":1,"1":13.41,"2":3.84,"3":2.12,"4":18.8,"5":90,"6":2.45,"7":2.68,"8":0.27,"9":1.48,"10":4.28,"11":0.91,"12":3.0,"13":1035},{"Unnamed: 0":42,"0":1,"1":13.88,"2":1.89,"3":2.59,"4":15.0,"5":101,"6":3.25,"7":3.56,"8":0.17,"9":1.7,"10":5.43,"11":0.88,"12":3.56,"13":1095},{"Unnamed: 0":43,"0":1,"1":13.24,"2":3.98,"3":2.29,"4":17.5,"5":103,"6":2.64,"7":2.63,"8":0.32,"9":1.66,"10":4.36,"11":0.82,"12":3.0,"13":680},{"Unnamed: 0":44,"0":1,"1":13.05,"2":1.77,"3":2.1,"4":17.0,"5":107,"6":3.0,"7":3.0,"8":0.28,"9":2.03,"10":5.04,"11":0.88,"12":3.35,"13":885},{"Unnamed: 0":45,"0":1,"1":14.21,"2":4.04,"3":2.44,"4":18.9,"5":111,"6":2.85,"7":2.65,"8":0.3,"9":1.25,"10":5.24,"11":0.87,"12":3.33,"13":1080},{"Unnamed: 0":46,"0":1,"1":14.38,"2":3.59,"3":2.28,"4":16.0,"5":102,"6":3.25,"7":3.17,"8":0.27,"9":2.19,"10":4.9,"11":1.04,"12":3.44,"13":1065},{"Unnamed: 0":47,"0":1,"1":13.9,"2":1.68,"3":2.12,"4":16.0,"5":101,"6":3.1,"7":3.39,"8":0.21,"9":2.14,"10":6.1,"11":0.91,"12":3.33,"13":985},{"Unnamed: 0":48,"0":1,"1":14.1,"2":2.02,"3":2.4,"4":18.8,"5":103,"6":2.75,"7":2.92,"8":0.32,"9":2.38,"10":6.2,"11":1.07,"12":2.75,"13":1060},{"Unnamed: 0":49,"0":1,"1":13.94,"2":1.73,"3":2.27,"4":17.4,"5":108,"6":2.88,"7":3.54,"8":0.32,"9":2.08,"10":8.9,"11":1.12,"12":3.1,"13":1260},{"Unnamed: 0":50,"0":1,"1":13.05,"2":1.73,"3":2.04,"4":12.4,"5":92,"6":2.72,"7":3.27,"8":0.17,"9":2.91,"10":7.2,"11":1.12,"12":2.91,"13":1150},{"Unnamed: 0":51,"0":1,"1":13.83,"2":1.65,"3":2.6,"4":17.2,"5":94,"6":2.45,"7":2.99,"8":0.22,"9":2.29,"10":5.6,"11":1.24,"12":3.37,"13":1265},{"Unnamed: 0":52,"0":1,"1":13.82,"2":1.75,"3":2.42,"4":14.0,"5":111,"6":3.88,"7":3.74,"8":0.32,"9":1.87,"10":7.05,"11":1.01,"12":3.26,"13":1190},{"Unnamed: 0":53,"0":1,"1":13.77,"2":1.9,"3":2.68,"4":17.1,"5":115,"6":3.0,"7":2.79,"8":0.39,"9":1.68,"10":6.3,"11":1.13,"12":2.93,"13":1375},{"Unnamed: 0":54,"0":1,"1":13.74,"2":1.67,"3":2.25,"4":16.4,"5":118,"6":2.6,"7":2.9,"8":0.21,"9":1.62,"10":5.85,"11":0.92,"12":3.2,"13":1060},{"Unnamed: 0":55,"0":1,"1":13.56,"2":1.73,"3":2.46,"4":20.5,"5":116,"6":2.96,"7":2.78,"8":0.2,"9":2.45,"10":6.25,"11":0.98,"12":3.03,"13":1120},{"Unnamed: 0":56,"0":1,"1":14.22,"2":1.7,"3":2.3,"4":16.3,"5":118,"6":3.2,"7":3.0,"8":0.26,"9":2.03,"10":6.38,"11":0.94,"12":3.31,"13":970},{"Unnamed: 0":57,"0":1,"1":13.29,"2":1.97,"3":2.68,"4":16.8,"5":102,"6":3.0,"7":3.23,"8":0.31,"9":1.66,"10":6.0,"11":1.07,"12":2.84,"13":1270},{"Unnamed: 0":58,"0":1,"1":13.72,"2":1.43,"3":2.5,"4":16.7,"5":108,"6":3.4,"7":3.67,"8":0.19,"9":2.04,"10":6.8,"11":0.89,"12":2.87,"13":1285},{"Unnamed: 0":59,"0":2,"1":12.37,"2":0.94,"3":1.36,"4":10.6,"5":88,"6":1.98,"7":0.57,"8":0.28,"9":0.42,"10":1.95,"11":1.05,"12":1.82,"13":520},{"Unnamed: 0":60,"0":2,"1":12.33,"2":1.1,"3":2.28,"4":16.0,"5":101,"6":2.05,"7":1.09,"8":0.63,"9":0.41,"10":3.27,"11":1.25,"12":1.67,"13":680},{"Unnamed: 0":61,"0":2,"1":12.64,"2":1.36,"3":2.02,"4":16.8,"5":100,"6":2.02,"7":1.41,"8":0.53,"9":0.62,"10":5.75,"11":0.98,"12":1.59,"13":450},{"Unnamed: 0":62,"0":2,"1":13.67,"2":1.25,"3":1.92,"4":18.0,"5":94,"6":2.1,"7":1.79,"8":0.32,"9":0.73,"10":3.8,"11":1.23,"12":2.46,"13":630},{"Unnamed: 0":63,"0":2,"1":12.37,"2":1.13,"3":2.16,"4":19.0,"5":87,"6":3.5,"7":3.1,"8":0.19,"9":1.87,"10":4.45,"11":1.22,"12":2.87,"13":420},{"Unnamed: 0":64,"0":2,"1":12.17,"2":1.45,"3":2.53,"4":19.0,"5":104,"6":1.89,"7":1.75,"8":0.45,"9":1.03,"10":2.95,"11":1.45,"12":2.23,"13":355},{"Unnamed: 0":65,"0":2,"1":12.37,"2":1.21,"3":2.56,"4":18.1,"5":98,"6":2.42,"7":2.65,"8":0.37,"9":2.08,"10":4.6,"11":1.19,"12":2.3,"13":678},{"Unnamed: 0":66,"0":2,"1":13.11,"2":1.01,"3":1.7,"4":15.0,"5":78,"6":2.98,"7":3.18,"8":0.26,"9":2.28,"10":5.3,"11":1.12,"12":3.18,"13":502},{"Unnamed: 0":67,"0":2,"1":12.37,"2":1.17,"3":1.92,"4":19.6,"5":78,"6":2.11,"7":2.0,"8":0.27,"9":1.04,"10":4.68,"11":1.12,"12":3.48,"13":510},{"Unnamed: 0":68,"0":2,"1":13.34,"2":0.94,"3":2.36,"4":17.0,"5":110,"6":2.53,"7":1.3,"8":0.55,"9":0.42,"10":3.17,"11":1.02,"12":1.93,"13":750},{"Unnamed: 0":69,"0":2,"1":12.21,"2":1.19,"3":1.75,"4":16.8,"5":151,"6":1.85,"7":1.28,"8":0.14,"9":2.5,"10":2.85,"11":1.28,"12":3.07,"13":718},{"Unnamed: 0":70,"0":2,"1":12.29,"2":1.61,"3":2.21,"4":20.4,"5":103,"6":1.1,"7":1.02,"8":0.37,"9":1.46,"10":3.05,"11":0.906,"12":1.82,"13":870},{"Unnamed: 0":71,"0":2,"1":13.86,"2":1.51,"3":2.67,"4":25.0,"5":86,"6":2.95,"7":2.86,"8":0.21,"9":1.87,"10":3.38,"11":1.36,"12":3.16,"13":410},{"Unnamed: 0":72,"0":2,"1":13.49,"2":1.66,"3":2.24,"4":24.0,"5":87,"6":1.88,"7":1.84,"8":0.27,"9":1.03,"10":3.74,"11":0.98,"12":2.78,"13":472},{"Unnamed: 0":73,"0":2,"1":12.99,"2":1.67,"3":2.6,"4":30.0,"5":139,"6":3.3,"7":2.89,"8":0.21,"9":1.96,"10":3.35,"11":1.31,"12":3.5,"13":985},{"Unnamed: 0":74,"0":2,"1":11.96,"2":1.09,"3":2.3,"4":21.0,"5":101,"6":3.38,"7":2.14,"8":0.13,"9":1.65,"10":3.21,"11":0.99,"12":3.13,"13":886},{"Unnamed: 0":75,"0":2,"1":11.66,"2":1.88,"3":1.92,"4":16.0,"5":97,"6":1.61,"7":1.57,"8":0.34,"9":1.15,"10":3.8,"11":1.23,"12":2.14,"13":428},{"Unnamed: 0":76,"0":2,"1":13.03,"2":0.9,"3":1.71,"4":16.0,"5":86,"6":1.95,"7":2.03,"8":0.24,"9":1.46,"10":4.6,"11":1.19,"12":2.48,"13":392},{"Unnamed: 0":77,"0":2,"1":11.84,"2":2.89,"3":2.23,"4":18.0,"5":112,"6":1.72,"7":1.32,"8":0.43,"9":0.95,"10":2.65,"11":0.96,"12":2.52,"13":500},{"Unnamed: 0":78,"0":2,"1":12.33,"2":0.99,"3":1.95,"4":14.8,"5":136,"6":1.9,"7":1.85,"8":0.35,"9":2.76,"10":3.4,"11":1.06,"12":2.31,"13":750},{"Unnamed: 0":79,"0":2,"1":12.7,"2":3.87,"3":2.4,"4":23.0,"5":101,"6":2.83,"7":2.55,"8":0.43,"9":1.95,"10":2.57,"11":1.19,"12":3.13,"13":463},{"Unnamed: 0":80,"0":2,"1":12.0,"2":0.92,"3":2.0,"4":19.0,"5":86,"6":2.42,"7":2.26,"8":0.3,"9":1.43,"10":2.5,"11":1.38,"12":3.12,"13":278},{"Unnamed: 0":81,"0":2,"1":12.72,"2":1.81,"3":2.2,"4":18.8,"5":86,"6":2.2,"7":2.53,"8":0.26,"9":1.77,"10":3.9,"11":1.16,"12":3.14,"13":714},{"Unnamed: 0":82,"0":2,"1":12.08,"2":1.13,"3":2.51,"4":24.0,"5":78,"6":2.0,"7":1.58,"8":0.4,"9":1.4,"10":2.2,"11":1.31,"12":2.72,"13":630},{"Unnamed: 0":83,"0":2,"1":13.05,"2":3.86,"3":2.32,"4":22.5,"5":85,"6":1.65,"7":1.59,"8":0.61,"9":1.62,"10":4.8,"11":0.84,"12":2.01,"13":515},{"Unnamed: 0":84,"0":2,"1":11.84,"2":0.89,"3":2.58,"4":18.0,"5":94,"6":2.2,"7":2.21,"8":0.22,"9":2.35,"10":3.05,"11":0.79,"12":3.08,"13":520},{"Unnamed: 0":85,"0":2,"1":12.67,"2":0.98,"3":2.24,"4":18.0,"5":99,"6":2.2,"7":1.94,"8":0.3,"9":1.46,"10":2.62,"11":1.23,"12":3.16,"13":450},{"Unnamed: 0":86,"0":2,"1":12.16,"2":1.61,"3":2.31,"4":22.8,"5":90,"6":1.78,"7":1.69,"8":0.43,"9":1.56,"10":2.45,"11":1.33,"12":2.26,"13":495},{"Unnamed: 0":87,"0":2,"1":11.65,"2":1.67,"3":2.62,"4":26.0,"5":88,"6":1.92,"7":1.61,"8":0.4,"9":1.34,"10":2.6,"11":1.36,"12":3.21,"13":562},{"Unnamed: 0":88,"0":2,"1":11.64,"2":2.06,"3":2.46,"4":21.6,"5":84,"6":1.95,"7":1.69,"8":0.48,"9":1.35,"10":2.8,"11":1.0,"12":2.75,"13":680},{"Unnamed: 0":89,"0":2,"1":12.08,"2":1.33,"3":2.3,"4":23.6,"5":70,"6":2.2,"7":1.59,"8":0.42,"9":1.38,"10":1.74,"11":1.07,"12":3.21,"13":625},{"Unnamed: 0":90,"0":2,"1":12.08,"2":1.83,"3":2.32,"4":18.5,"5":81,"6":1.6,"7":1.5,"8":0.52,"9":1.64,"10":2.4,"11":1.08,"12":2.27,"13":480},{"Unnamed: 0":91,"0":2,"1":12.0,"2":1.51,"3":2.42,"4":22.0,"5":86,"6":1.45,"7":1.25,"8":0.5,"9":1.63,"10":3.6,"11":1.05,"12":2.65,"13":450},{"Unnamed: 0":92,"0":2,"1":12.69,"2":1.53,"3":2.26,"4":20.7,"5":80,"6":1.38,"7":1.46,"8":0.58,"9":1.62,"10":3.05,"11":0.96,"12":2.06,"13":495},{"Unnamed: 0":93,"0":2,"1":12.29,"2":2.83,"3":2.22,"4":18.0,"5":88,"6":2.45,"7":2.25,"8":0.25,"9":1.99,"10":2.15,"11":1.15,"12":3.3,"13":290},{"Unnamed: 0":94,"0":2,"1":11.62,"2":1.99,"3":2.28,"4":18.0,"5":98,"6":3.02,"7":2.26,"8":0.17,"9":1.35,"10":3.25,"11":1.16,"12":2.96,"13":345},{"Unnamed: 0":95,"0":2,"1":12.47,"2":1.52,"3":2.2,"4":19.0,"5":162,"6":2.5,"7":2.27,"8":0.32,"9":3.28,"10":2.6,"11":1.16,"12":2.63,"13":937},{"Unnamed: 0":96,"0":2,"1":11.81,"2":2.12,"3":2.74,"4":21.5,"5":134,"6":1.6,"7":0.99,"8":0.14,"9":1.56,"10":2.5,"11":0.95,"12":2.26,"13":625},{"Unnamed: 0":97,"0":2,"1":12.29,"2":1.41,"3":1.98,"4":16.0,"5":85,"6":2.55,"7":2.5,"8":0.29,"9":1.77,"10":2.9,"11":1.23,"12":2.74,"13":428},{"Unnamed: 0":98,"0":2,"1":12.37,"2":1.07,"3":2.1,"4":18.5,"5":88,"6":3.52,"7":3.75,"8":0.24,"9":1.95,"10":4.5,"11":1.04,"12":2.77,"13":660},{"Unnamed: 0":99,"0":2,"1":12.29,"2":3.17,"3":2.21,"4":18.0,"5":88,"6":2.85,"7":2.99,"8":0.45,"9":2.81,"10":2.3,"11":1.42,"12":2.83,"13":406},{"Unnamed: 0":100,"0":2,"1":12.08,"2":2.08,"3":1.7,"4":17.5,"5":97,"6":2.23,"7":2.17,"8":0.26,"9":1.4,"10":3.3,"11":1.27,"12":2.96,"13":710},{"Unnamed: 0":101,"0":2,"1":12.6,"2":1.34,"3":1.9,"4":18.5,"5":88,"6":1.45,"7":1.36,"8":0.29,"9":1.35,"10":2.45,"11":1.04,"12":2.77,"13":562},{"Unnamed: 0":102,"0":2,"1":12.34,"2":2.45,"3":2.46,"4":21.0,"5":98,"6":2.56,"7":2.11,"8":0.34,"9":1.31,"10":2.8,"11":0.8,"12":3.38,"13":438},{"Unnamed: 0":103,"0":2,"1":11.82,"2":1.72,"3":1.88,"4":19.5,"5":86,"6":2.5,"7":1.64,"8":0.37,"9":1.42,"10":2.06,"11":0.94,"12":2.44,"13":415},{"Unnamed: 0":104,"0":2,"1":12.51,"2":1.73,"3":1.98,"4":20.5,"5":85,"6":2.2,"7":1.92,"8":0.32,"9":1.48,"10":2.94,"11":1.04,"12":3.57,"13":672},{"Unnamed: 0":105,"0":2,"1":12.42,"2":2.55,"3":2.27,"4":22.0,"5":90,"6":1.68,"7":1.84,"8":0.66,"9":1.42,"10":2.7,"11":0.86,"12":3.3,"13":315},{"Unnamed: 0":106,"0":2,"1":12.25,"2":1.73,"3":2.12,"4":19.0,"5":80,"6":1.65,"7":2.03,"8":0.37,"9":1.63,"10":3.4,"11":1.0,"12":3.17,"13":510},{"Unnamed: 0":107,"0":2,"1":12.72,"2":1.75,"3":2.28,"4":22.5,"5":84,"6":1.38,"7":1.76,"8":0.48,"9":1.63,"10":3.3,"11":0.88,"12":2.42,"13":488},{"Unnamed: 0":108,"0":2,"1":12.22,"2":1.29,"3":1.94,"4":19.0,"5":92,"6":2.36,"7":2.04,"8":0.39,"9":2.08,"10":2.7,"11":0.86,"12":3.02,"13":312},{"Unnamed: 0":109,"0":2,"1":11.61,"2":1.35,"3":2.7,"4":20.0,"5":94,"6":2.74,"7":2.92,"8":0.29,"9":2.49,"10":2.65,"11":0.96,"12":3.26,"13":680},{"Unnamed: 0":110,"0":2,"1":11.46,"2":3.74,"3":1.82,"4":19.5,"5":107,"6":3.18,"7":2.58,"8":0.24,"9":3.58,"10":2.9,"11":0.75,"12":2.81,"13":562},{"Unnamed: 0":111,"0":2,"1":12.52,"2":2.43,"3":2.17,"4":21.0,"5":88,"6":2.55,"7":2.27,"8":0.26,"9":1.22,"10":2.0,"11":0.9,"12":2.78,"13":325},{"Unnamed: 0":112,"0":2,"1":11.76,"2":2.68,"3":2.92,"4":20.0,"5":103,"6":1.75,"7":2.03,"8":0.6,"9":1.05,"10":3.8,"11":1.23,"12":2.5,"13":607},{"Unnamed: 0":113,"0":2,"1":11.41,"2":0.74,"3":2.5,"4":21.0,"5":88,"6":2.48,"7":2.01,"8":0.42,"9":1.44,"10":3.08,"11":1.1,"12":2.31,"13":434},{"Unnamed: 0":114,"0":2,"1":12.08,"2":1.39,"3":2.5,"4":22.5,"5":84,"6":2.56,"7":2.29,"8":0.43,"9":1.04,"10":2.9,"11":0.93,"12":3.19,"13":385},{"Unnamed: 0":115,"0":2,"1":11.03,"2":1.51,"3":2.2,"4":21.5,"5":85,"6":2.46,"7":2.17,"8":0.52,"9":2.01,"10":1.9,"11":1.71,"12":2.87,"13":407},{"Unnamed: 0":116,"0":2,"1":11.82,"2":1.47,"3":1.99,"4":20.8,"5":86,"6":1.98,"7":1.6,"8":0.3,"9":1.53,"10":1.95,"11":0.95,"12":3.33,"13":495},{"Unnamed: 0":117,"0":2,"1":12.42,"2":1.61,"3":2.19,"4":22.5,"5":108,"6":2.0,"7":2.09,"8":0.34,"9":1.61,"10":2.06,"11":1.06,"12":2.96,"13":345},{"Unnamed: 0":118,"0":2,"1":12.77,"2":3.43,"3":1.98,"4":16.0,"5":80,"6":1.63,"7":1.25,"8":0.43,"9":0.83,"10":3.4,"11":0.7,"12":2.12,"13":372},{"Unnamed: 0":119,"0":2,"1":12.0,"2":3.43,"3":2.0,"4":19.0,"5":87,"6":2.0,"7":1.64,"8":0.37,"9":1.87,"10":1.28,"11":0.93,"12":3.05,"13":564},{"Unnamed: 0":120,"0":2,"1":11.45,"2":2.4,"3":2.42,"4":20.0,"5":96,"6":2.9,"7":2.79,"8":0.32,"9":1.83,"10":3.25,"11":0.8,"12":3.39,"13":625},{"Unnamed: 0":121,"0":2,"1":11.56,"2":2.05,"3":3.23,"4":28.5,"5":119,"6":3.18,"7":5.08,"8":0.47,"9":1.87,"10":6.0,"11":0.93,"12":3.69,"13":465},{"Unnamed: 0":122,"0":2,"1":12.42,"2":4.43,"3":2.73,"4":26.5,"5":102,"6":2.2,"7":2.13,"8":0.43,"9":1.71,"10":2.08,"11":0.92,"12":3.12,"13":365},{"Unnamed: 0":123,"0":2,"1":13.05,"2":5.8,"3":2.13,"4":21.5,"5":86,"6":2.62,"7":2.65,"8":0.3,"9":2.01,"10":2.6,"11":0.73,"12":3.1,"13":380},{"Unnamed: 0":124,"0":2,"1":11.87,"2":4.31,"3":2.39,"4":21.0,"5":82,"6":2.86,"7":3.03,"8":0.21,"9":2.91,"10":2.8,"11":0.75,"12":3.64,"13":380},{"Unnamed: 0":125,"0":2,"1":12.07,"2":2.16,"3":2.17,"4":21.0,"5":85,"6":2.6,"7":2.65,"8":0.37,"9":1.35,"10":2.76,"11":0.86,"12":3.28,"13":378},{"Unnamed: 0":126,"0":2,"1":12.43,"2":1.53,"3":2.29,"4":21.5,"5":86,"6":2.74,"7":3.15,"8":0.39,"9":1.77,"10":3.94,"11":0.69,"12":2.84,"13":352},{"Unnamed: 0":127,"0":2,"1":11.79,"2":2.13,"3":2.78,"4":28.5,"5":92,"6":2.13,"7":2.24,"8":0.58,"9":1.76,"10":3.0,"11":0.97,"12":2.44,"13":466},{"Unnamed: 0":128,"0":2,"1":12.37,"2":1.63,"3":2.3,"4":24.5,"5":88,"6":2.22,"7":2.45,"8":0.4,"9":1.9,"10":2.12,"11":0.89,"12":2.78,"13":342},{"Unnamed: 0":129,"0":2,"1":12.04,"2":4.3,"3":2.38,"4":22.0,"5":80,"6":2.1,"7":1.75,"8":0.42,"9":1.35,"10":2.6,"11":0.79,"12":2.57,"13":580},{"Unnamed: 0":130,"0":3,"1":12.86,"2":1.35,"3":2.32,"4":18.0,"5":122,"6":1.51,"7":1.25,"8":0.21,"9":0.94,"10":4.1,"11":0.76,"12":1.29,"13":630},{"Unnamed: 0":131,"0":3,"1":12.88,"2":2.99,"3":2.4,"4":20.0,"5":104,"6":1.3,"7":1.22,"8":0.24,"9":0.83,"10":5.4,"11":0.74,"12":1.42,"13":530},{"Unnamed: 0":132,"0":3,"1":12.81,"2":2.31,"3":2.4,"4":24.0,"5":98,"6":1.15,"7":1.09,"8":0.27,"9":0.83,"10":5.7,"11":0.66,"12":1.36,"13":560},{"Unnamed: 0":133,"0":3,"1":12.7,"2":3.55,"3":2.36,"4":21.5,"5":106,"6":1.7,"7":1.2,"8":0.17,"9":0.84,"10":5.0,"11":0.78,"12":1.29,"13":600},{"Unnamed: 0":134,"0":3,"1":12.51,"2":1.24,"3":2.25,"4":17.5,"5":85,"6":2.0,"7":0.58,"8":0.6,"9":1.25,"10":5.45,"11":0.75,"12":1.51,"13":650},{"Unnamed: 0":135,"0":3,"1":12.6,"2":2.46,"3":2.2,"4":18.5,"5":94,"6":1.62,"7":0.66,"8":0.63,"9":0.94,"10":7.1,"11":0.73,"12":1.58,"13":695},{"Unnamed: 0":136,"0":3,"1":12.25,"2":4.72,"3":2.54,"4":21.0,"5":89,"6":1.38,"7":0.47,"8":0.53,"9":0.8,"10":3.85,"11":0.75,"12":1.27,"13":720},{"Unnamed: 0":137,"0":3,"1":12.53,"2":5.51,"3":2.64,"4":25.0,"5":96,"6":1.79,"7":0.6,"8":0.63,"9":1.1,"10":5.0,"11":0.82,"12":1.69,"13":515},{"Unnamed: 0":138,"0":3,"1":13.49,"2":3.59,"3":2.19,"4":19.5,"5":88,"6":1.62,"7":0.48,"8":0.58,"9":0.88,"10":5.7,"11":0.81,"12":1.82,"13":580},{"Unnamed: 0":139,"0":3,"1":12.84,"2":2.96,"3":2.61,"4":24.0,"5":101,"6":2.32,"7":0.6,"8":0.53,"9":0.81,"10":4.92,"11":0.89,"12":2.15,"13":590},{"Unnamed: 0":140,"0":3,"1":12.93,"2":2.81,"3":2.7,"4":21.0,"5":96,"6":1.54,"7":0.5,"8":0.53

### Reading HTML
- https://github.com/BrambleXu/pydata-notebook/blob/master/examples/fdic_failed_bank_list.html

In [64]:
url='https://www.fdic.gov/bank-failures/failed-bank-list'
dfs=pd.read_html(url)
dfs

[                                            Bank Name                City  \
 0             Community Bank and Trust - West Georgia            LaGrange
 1                   Metropolitan Capital Bank & Trust             Chicago
 2                        The Santa Anna National Bank          Santa Anna
 3                                Pulaski Savings Bank             Chicago
 4                  The First National Bank of Lindsay             Lindsay
 5               Republic First Bank dba Republic Bank        Philadelphia
 6                                       Citizens Bank            Sac City
 7                            Heartland Tri-State Bank             Elkhart
 8                                 First Republic Bank       San Francisco
 9                                      Signature Bank            New York
 10                                Silicon Valley Bank         Santa Clara
 11                                  Almena State Bank              Almena
 12                         First City Bank of Florida   Fort Walton Beach
 13                               The First State Bank       Barboursville
 14                                 Ericson State Bank             Ericson
 15                   City National Bank of New Jersey              Newark
 16                                      Resolute Bank              Maumee
 17                              Louisa Community Bank              Louisa
 18                               The Enloe State Bank              Cooper
 19                Washington Federal Bank for Savings             Chicago
 20    The Farmers and Merchants State Bank of Argonia             Argonia
 21                                Fayette County Bank          Saint Elmo
 22  Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee
 23                                     First NBC Bank         New Orleans
 24                                      Proficio Bank  Cottonwood Heights

             State   Cert                Acquiring Institution  \
 0         Georgia  25796                          Anchor Bank
 1        Illinois  57488              First Independence Bank
 2           Texas   5520            Coleman County State Bank
 3        Illinois  28611                      Millennium Bank
 4        Oklahoma   4134               First Bank & Trust Co.
 5    Pennsylvania  27332    Fulton Bank, National Association
 6            Iowa   8758            Iowa Trust & Savings Bank
 7          Kansas  25851               Dream First Bank, N.A.
 8      California  59017            JPMorgan Chase Bank, N.A.
 9        New York  57053                  Flagstar Bank, N.A.
 10     California  24735  First–Citizens Bank & Trust Company
 11         Kansas  15426                          Equity Bank
 12        Florida  16748            United Fidelity Bank, fsb
 13  West Virginia  14361                       MVB Bank, Inc.
 14       Nebraska  18265           Farmers and Merchants Bank
 15     New Jersey  21111                      Industrial Bank
 16           Ohio  58317                   Buckeye State Bank
 17       Kentucky  58112    Kentucky Farmers Bank Corporation
 18          Texas  10716                   Legend Bank, N. A.
 19       Illinois  30570                   Royal Savings Bank
 20         Kansas  17719                          Conway Bank
 21       Illinois   1802            United Fidelity Bank, fsb
 22      Wisconsin  30003  First-Citizens Bank & Trust Company
 23      Louisiana  58302                         Whitney Bank
 24           Utah  35495                    Cache Valley Bank

          Closing Date  Fund  Sort ascending
 0         May 1, 2026                 10551
 1    January 30, 2026                 10550
 2       June 27, 2025                 10549
 3    January 17, 2025                 10548
 4    October 18, 2024                 10547
 5      April 26, 2024                 10546
 6    November 3, 2023                 10545
 7       July 28, 2023                 10544
 8         May 1, 2023                 10543
 9      March 12, 2023                 10540
 10     March 10, 2023                 10539
 11   October 23, 2020                 10538
 12   October 16, 2020                 10537
 13      April 3, 2020                 10536
 14  February 14, 2020                 10535
 15   November 1, 2019                 10534
 16   October 25, 2019                 10533
 17   October 25, 2019                 10532
 18       May 31, 2019                 10531
 19  December 15, 2017                 10530
 20   October 13, 2017                 10529
 21       May 26, 2017                 10528
 22        May 5, 2017                 10527
 23     April 28, 2017                 10526
 24      March 3, 2017                 10525  ]

### Reading Execl files

In [78]:
dfe=pd.read_excel('Excel_Sample.xlsx')
dfe.head()

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

### Pickling
- In pandas, pickle is a way to save Python objects (like DataFrames, lists, dictionaries, models, etc.) into a binary file so you can load them back later.

- Saving machine learning datasets
- Saving trained AI/ML models
- Faster loading than CSV
- Preserving exact Python object structure

In [79]:
dfe.to_pickle("df_execl")

In [ ]:
dfe=pd.read_pickle("df_execl")